on:
  push

env:
  targetEnv: Dev

name: Azure Bicep Deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep template
    - name: Run Bicep deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        scope: subscription
        region: westeurope
        template: ./Bicep-Templates/main.bicep
        parameters: webAppName=wthapp-${{ env.targetEnv }}
