on:
  workflow_dispatch:
   inputs:
    appenv:
      type: choice
      description: Choose the target environment
      options: 
        - dev
        - test
        - prod

name: Azure Bicep Deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        region: westeurope
        scope: subscription
        template: ./Bicep-Templates/main.bicep
        parameters: webAppName=wthapp-${{ github.event.inputs.appenv }}
